// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9PZBI9pXCEmIWVzvswBjktILkVFv-HYg',
    appId: '1:443955707397:web:7a2865a3f1b04f7b57e66c',
    messagingSenderId: '443955707397',
    projectId: 'laboratorio-5b7ee',
    authDomain: 'laboratorio-5b7ee.firebaseapp.com',
    storageBucket: 'laboratorio-5b7ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjIIvs82OWm9WOVOjGBg79j9PVGvNBfPU',
    appId: '1:443955707397:android:dd9ca4826b2a74e657e66c',
    messagingSenderId: '443955707397',
    projectId: 'laboratorio-5b7ee',
    storageBucket: 'laboratorio-5b7ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPVzyyePDgEdYnkpRQIRX1MgG1j8G610E',
    appId: '1:443955707397:ios:811c0d58757614f757e66c',
    messagingSenderId: '443955707397',
    projectId: 'laboratorio-5b7ee',
    storageBucket: 'laboratorio-5b7ee.appspot.com',
    iosBundleId: 'com.example.practica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPVzyyePDgEdYnkpRQIRX1MgG1j8G610E',
    appId: '1:443955707397:ios:49414388c25b73bd57e66c',
    messagingSenderId: '443955707397',
    projectId: 'laboratorio-5b7ee',
    storageBucket: 'laboratorio-5b7ee.appspot.com',
    iosBundleId: 'com.example.practica.RunnerTests',
  );
}
